# Exported from Render on 2025-06-23T15:31:30Z
services:
  - type: web
    name: RECEIPT-PROCESSOR
    runtime: python
    repo: https://github.com/briankaplan/RECEIPT-PROCESSOR
    plan: free
    region: oregon
    buildCommand: pip install -r requirements_minimal.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 300 --workers 1 --worker-class sync --max-requests 1000 --preload
    autoDeployTrigger: commit
    healthCheckPath: /health
    branch: main
    envVars:
      # Core Flask Configuration
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FLASK_DEBUG
        value: "false"
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        sync: false  # Set in Render dashboard
      - key: UPLOAD_FOLDER
        value: uploads
      - key: MAX_CONTENT_LENGTH
        value: "16777216"
      - key: LOG_LEVEL
        value: INFO
      
      # MongoDB Database
      - key: MONGO_URI
        sync: false  # Set in Render dashboard
      - key: MONGODB_URI
        sync: false  # Set in Render dashboard
      - key: MONGODB_DATABASE
        value: expense
      - key: MONGODB_COLLECTION
        value: receipts
      
      # Processing Configuration
      - key: MAX_CONCURRENT_PROCESSING
        value: "3"
      - key: MAX_EMAILS_PER_BATCH
        value: "50"
      - key: PROCESSING_DAYS
        value: "30"
      - key: AI_CONFIDENCE_THRESHOLD
        value: "0.7"
      - key: AMOUNT_TOLERANCE
        value: "0.01"
      - key: DATE_TOLERANCE_DAYS
        value: "3"
      - key: LOCAL_EXPORT_ENABLED
        value: "true"
      
      # Teller Banking API
      - key: TELLER_APPLICATION_ID
        sync: false  # Set in Render dashboard
      - key: TELLER_ENVIRONMENT
        value: development
      - key: TELLER_API_URL
        value: https://api.teller.io
      - key: TELLER_API_VERSION
        value: 2020-10-12
      - key: TELLER_WEBHOOK_URL
        value: https://receipt-processor.onrender.com/teller/webhook
      - key: TELLER_SIGNING_SECRET
        sync: false  # Set in Render dashboard
      - key: TELLER_SIGNING_KEY
        sync: false  # Set in Render dashboard
      - key: TELLER_CERT_PATH
        value: /etc/secrets/teller_certificate.b64
      - key: TELLER_KEY_PATH
        value: /etc/secrets/teller_private_key.b64
      
      # AI Services - HUGGINGFACE ONLY (NO OPENAI)
      - key: HUGGINGFACE_API_KEY
        sync: false  # Set in Render dashboard
      
      # Cost Protection Limits (RECOMMENDED FOR MONTHLY PLAN)
      - key: HUGGINGFACE_DAILY_LIMIT
        value: "200"  # Conservative daily limit
      - key: HUGGINGFACE_MONTHLY_LIMIT
        value: "5000"  # Monthly safety limit
      - key: AI_REQUEST_TIMEOUT
        value: "15"  # Shorter timeouts
      - key: AI_RETRY_ATTEMPTS
        value: "1"  # Fewer retries
      - key: FALLBACK_TO_RULES_THRESHOLD
        value: "0.8"  # Fall back to rules at 80% usage
      
      # Cloudflare R2 Storage - SET IN RENDER DASHBOARD
      - key: R2_ENDPOINT
        sync: false  # Set in Render dashboard
      - key: R2_ACCESS_KEY
        sync: false  # Set in Render dashboard
      - key: R2_SECRET_KEY
        sync: false  # Set in Render dashboard
      - key: R2_BUCKET
        value: expensesbk
      - key: R2_PUBLIC_URL
        sync: false  # Set in Render dashboard
      
      # Gmail API Configuration - Account 1 (Personal)
      - key: GMAIL_ACCOUNT_1_EMAIL
        value: kaplan.brian@gmail.com
      - key: GMAIL_ACCOUNT_1_DISPLAY_NAME
        value: "Personal Gmail"
      - key: GMAIL_ACCOUNT_1_ENABLED
        value: "true"
      - key: GMAIL_ACCOUNT_1_PICKLE_FILE
        value: /etc/secrets/kaplan_brian_gmail.b64
      - key: GMAIL_ACCOUNT_1_PORT
        value: "8080"
      
      # Gmail API Configuration - Account 2 (Down Home Business)
      - key: GMAIL_ACCOUNT_2_EMAIL
        value: brian@downhome.com
      - key: GMAIL_ACCOUNT_2_DISPLAY_NAME
        value: "Down Home Business"
      - key: GMAIL_ACCOUNT_2_ENABLED
        value: "true"
      - key: GMAIL_ACCOUNT_2_PICKLE_FILE
        value: /etc/secrets/brian_downhome.b64
      - key: GMAIL_ACCOUNT_2_PORT
        value: "8081"
      
      # Gmail API Configuration - Account 3 (Music City Rodeo)
      - key: GMAIL_ACCOUNT_3_EMAIL
        value: brian@musiccityrodeo.com
      - key: GMAIL_ACCOUNT_3_DISPLAY_NAME
        value: "Music City Rodeo"
      - key: GMAIL_ACCOUNT_3_ENABLED
        value: "true"
      - key: GMAIL_ACCOUNT_3_PICKLE_FILE
        value: /etc/secrets/brian_musiccityrodeo.b64
      - key: GMAIL_ACCOUNT_3_PORT
        value: "8082"
      
      # Google Services Configuration
      - key: GOOGLE_CREDENTIALS_PATH
        value: /etc/secrets/gmail_credentials.b64
      - key: GOOGLE_SERVICE_ACCOUNT_PATH
        value: /etc/secrets/service_account.b64
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/service_account.b64
      - key: GOOGLE_VISION_API_KEY
        sync: false  # Set in Render dashboard
      - key: GOOGLE_SHEETS_ID
        sync: false  # Set in Render dashboard
      - key: GOOGLE_SHEETS_NAME
        value: "Receipt Dashboard"

version: "1" 